# -*- coding: utf-8 -*-
"""KendallTau - SurveyBuilder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pVSVBUvAo1PvIS65mHV-EqeR1Im5N5is
"""

import numpy as np
import pandas as pd
from scipy.stats import kendalltau

# ---------------------------------------------------------
# Example: dummy data
# rows = items, columns = raters
# Replace this with your real data (e.g. from CSV)
# ---------------------------------------------------------

survey_builder = np.array([
    [5, 1, 5, 2, 3, 1, 5, 1, 4, 1],
[5, 1, 5, 2, 4, 1, 5, 1, 4, 2],
[5, 1, 5, 2, 5, 1, 5, 1, 3, 1],
[4, 2, 4, 2, 3, 1, 5, 2, 3, 2],
[5, 1, 5, 1, 5, 1, 5, 1, 5, 1],
[5, 2, 4, 3, 4, 1, 4, 2, 3, 1],
[5, 1, 4, 5, 5, 1, 4, 1, 4, 1],
    [5, 1, 5, 2, 5, 1, 5, 1, 5, 2],
[5, 1, 5, 1, 4, 1, 4, 1, 4, 1],
[4, 2, 4, 1, 3, 2, 5, 2, 5, 2],
[4, 1, 4, 1, 5, 2, 5, 2, 4, 1],
[4, 4, 3, 2, 3, 2, 3, 3, 3, 1],
[3, 3, 3, 3, 3, 2, 5, 2, 3, 2]
])

limesurvey = np.array([
    [3, 3, 2, 3, 2, 1, 4, 2, 1, 4],
[3, 3, 3, 3, 4, 3, 2, 3, 3, 3],
[3, 4, 3, 4, 4, 1, 2, 4, 3, 4],
[4, 3, 4, 4, 4, 1, 3, 2, 3, 4],
[3, 2, 3, 1, 3, 2, 4, 3, 4, 3],
[2, 3, 3, 4, 3, 2, 2, 3, 2, 3],
[5, 1, 3, 5, 4, 2, 4, 1, 3, 4],
    [2, 2, 3, 5, 3, 3, 3, 3, 2, 3],
[4, 2, 3, 3, 4, 1, 2, 3, 3, 4],
[2, 3, 3, 3, 4, 2, 3, 3, 4, 3],
[3, 2, 4, 2, 4, 2, 3, 3, 4, 2],
[3, 3, 3, 2, 5, 2, 3, 3, 3, 4],
[4, 2, 3, 3, 3, 2, 2, 4, 2, 3]
    ]
)

def compute_correlation(data: np.array):
    n_raters = len(data)  # number of raters

    data = data.transpose()

    # Put into a DataFrame for convenience
    rater_names = [f"Rater_{i+1}" for i in range(n_raters)]
    df = pd.DataFrame(data=data, columns=rater_names)

    # ---------------------------------------------------------
    # Compute pairwise Kendall's tau between all 7 raters
    # ---------------------------------------------------------
    tau_matrix = pd.DataFrame(
        np.zeros((n_raters, n_raters)),
        index=rater_names,
        columns=rater_names,
    )

    pval_matrix = pd.DataFrame(
        np.zeros((n_raters, n_raters)),
        index=rater_names,
        columns=rater_names,
    )

    for i in range(n_raters):
        for j in range(n_raters):
            if i == j:
                tau_matrix.iloc[i, j] = 1.0
                pval_matrix.iloc[i, j] = 0.0
            elif i < j:
                tau, pval = kendalltau(df.iloc[:, i], df.iloc[:, j])
                tau_matrix.iloc[i, j] = tau
                tau_matrix.iloc[j, i] = tau
                pval_matrix.iloc[i, j] = pval
                pval_matrix.iloc[j, i] = pval

    return {'tau': tau_matrix.mean().mean(),
            'pval': pval_matrix.mean().mean()}

sb = compute_correlation(survey_builder)
print('SurveyBuilder')
print(f'TAU: {sb["tau"]}')
print(f'p-val: {sb["pval"]}')

sb = compute_correlation(limesurvey)
print('SurveyBuilder')
print(f'TAU: {sb["tau"]}')
print(f'p-val: {sb["pval"]}')